// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Blazor;
    using Microsoft.AspNetCore.Blazor.Components;
    public class TestComponent : Microsoft.AspNetCore.Blazor.Components.BlazorComponent
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(Microsoft.AspNetCore.Blazor.RenderTree.RenderTreeBuilder builder)
        {
            base.BuildRenderTree(builder);
#line 1 "x:\dir\subdir\Test\TestComponent.cshtml"
  
    var link = "link";
    var teacherId = "1234567890";
    var startDate = DateTime.Now;

#line default
#line hidden
            builder.AddContent(0, "\n");
            builder.OpenElement(1, "button");
            builder.AddAttribute(2, "onkeydown", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetEventHandlerValue<Microsoft.AspNetCore.Blazor.UIKeyboardEventArgs>($"window.location.href = '/teacher/{teacherId}/';"));
            builder.AddAttribute(3, "onclick", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetEventHandlerValue<Microsoft.AspNetCore.Blazor.UIMouseEventArgs>("window.location.href" + " =" + " \'/teacher/" + (teacherId) + "/\';"));
            builder.AddContent(4, "More info...");
            builder.CloseElement();
            builder.AddContent(5, "\n\n");
            builder.OpenElement(6, "a");
            builder.AddAttribute(7, "class", "btn btn-secondary float-left");
            builder.AddAttribute(8, "href", "fetchdata/" + (startDate.AddDays(-5).ToString("yyyy-MM-dd")));
            builder.AddContent(9, "Link");
            builder.CloseElement();
            builder.AddContent(10, "\n\n");
            builder.OpenElement(11, "button");
            builder.AddAttribute(12, "onclick", Microsoft.AspNetCore.Blazor.Components.BindMethods.GetEventHandlerValue<Microsoft.AspNetCore.Blazor.UIMouseEventArgs>((link) + "b"));
            builder.AddContent(13, "More info...");
            builder.CloseElement();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
